### DISCUSSION TITLE
Decide how to organize CI actions

### DISCUSSION THREAD

**Discussion by brylie** [cc-archive/vocabulary-legacy#970] [Ideas]
For context, we have recently refactored this project so there is only a single `src/` directory containing all package code.

We currently have three CI actions defined:

- fonts
- vocabulary
- vue-vocabulary

Each of the three CI actions has nearly identical structure:

- `on:` definitions to determine when the action should run
- `env:` variables that may no longer be needed
- `jobs` to execute the following actions
    - `setup` to install Node.js, cache node modules, and install project dependencies
    - `lint` (depends on setup) to lint the code
    - `unit` (depends on setup) to run unit tests
    - `build` (depends on setup) to run the build process

Not only are there duplicate steps within each of the above jobs (such as installing node and project dependencies), it is likely that we no longer need three separate actions.

So, we should determine how best to reorganize our CI script(s) in order to reduce duplication and resource usage as well as making it clear for developers what parts are breaking when there are errors.

Please discuss and upvote the suggestions below to show your support or add modifications. Likewise, feel free to add other proposals.

**Comment by brylie** [comment]
One solution would be to consolidate all CI code into a single action, such as `continuous_integration.yaml`. The CI file would have a structure somewhat like the code below. Note that the code is speculative right now and intended only to illustrate the idea.


<details>

<summary>continuous-integration.yml</summary>

```yaml
name: Continuous integration

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true # is this needed?
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true # is this needed?

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm install --no-audit

  lint:
    name: Lint
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps: # will it work to only have the lint step here?
      - name: Run lint
        run: npm run lint

  unit:
    name: Unit tests
    defaults:
      run:
        working-directory: "packages/vocabulary"
    runs-on: ubuntu-latest
    needs: setup

    steps: # Will it work to only have the "run tests" step here?
      - name: Run tests
        run: npm run test:unit

  build:
    name: Build
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps: # Will it work to only have the "run build" step here?
      - name: Run build
        run: npm run build:storybook
```
</details>

**Reply by brylie** [reply]
Some pros/cons of this step might be:

Pros
- efficient resource usage, since there is only one `setup` process that does the heavy lifting
- only one definition file is needed

Cons
- error messages may be a bit more difficult for developers to understand, since the "continuous integration" process consists of lint, unit, and build tasks

**Comment by MuluhGodson** [comment]
I totally agree, the three scripts I think run the same commands so it will make sense resource-wise to use one file as you suggested. `continuous_integration.yaml`

For local testing of github actions I am using a package:
https://github.com/nektos/act
It would be helpful as concerns testing the script locally, in case it is made into an issue and assigned.

**Comment by brylie** [comment]
Alternatively, we can separate the continuous integration scripts along the lines of their purpose, such as

- lint
- unit test
- build

In the above division, we would end up with three files, each demonstrated in a relevant section below.

<details>

<summary>ci-lint.yml</summary>

```yaml
name: Lint

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true # Is this needed?
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true # Is this needed?

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  lint:
    name: Lint
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps: # Will this work as expected with only the "run lint" step?
      - name: Run lint
        run: npm run lint
```
</details>


<details>

<summary>ci-test.yml</summary>

```yaml
name: Unit test

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true # Is this needed?
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true # Is this needed?

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  unit:
    name: Unit tests
    defaults:
      run:
        working-directory: "packages/fonts"
    runs-on: ubuntu-latest
    needs: setup

    steps: # Will this work with only the "run tests" step?
      - name: Run tests
        run: npm run test:unit
```
</details>

<details>

<summary>ci-build.yml</summary>

```yaml
name: Build

on: # TODO: determine best "on" configuration
  push:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main
  pull_request:
    paths:
      - "packages/**"
      - "scripts/**"
      - "src/**"
    branches:
      - main

env:
  CI: true # Is this needed?
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true # Is this needed?

jobs:
  setup:
    name: Setup
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.1"

      - id: cache-node-modules
        name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm # npm caches files in ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm install --no-audit

  build:
    name: Build
    defaults:
      run:
        working-directory: "/"
    runs-on: ubuntu-latest
    needs: setup

    steps: # Will this work with only the "run build" step defined?
      - name: Run build
        run: npm run build:storybook
```
</details>
