### ISSUE TITLE
[Bug] Bulma minireset.css is breaking formatting in downstream projects

### ISSUE THREAD

**Issue by TimidRobot** [cc-archive/vocabulary-legacy#1037]
## Description
Vocabulary `v2020.11.3` CSS is overly generic. It breaks basic formatting. Any HTML that is not explicitly styled (and some that is) looks terrible.

Examples:
```css
html,body,p,ol,ul,li,dl,dt,dd,blockquote,figure,fieldset,legend,textarea,pre,iframe,hr,h1,h2,h3,h4,h5,h6 {
    margin: 0;
    padding: 0;
}
```
```css
ul {
    list-style: none; 
}
```
```css
table {
    border-collapse: collapse;
    border-spacing: 0;
}

td,th {
    padding: 0;
}
```

## Reproduction
De-minnify https://unpkg.com/@creativecommons/vocabulary@v2020.11.3/css/vocabulary.css

## Expectation
CSS should be neither overly specific (results in a lot of duplication) nor overly generic (breaks rendering, violates principle of least astonishment).
