### ISSUE TITLE
Update Section Divider Styling 

### ISSUE THREAD

**Issue by Audiosutras** [cc-archive/vocabulary-legacy#513]
## Problem

`<hr class="divider">` needs to have its styling updated for 4.0 licenses.

### Actual 
![Screen Shot 2020-07-16 at 5 50 40 AM](https://user-images.githubusercontent.com/37882933/87657636-16e64e00-c729-11ea-95c2-a0c5a14eef95.png)
![Screen Shot 2020-07-16 at 5 50 27 AM](https://user-images.githubusercontent.com/37882933/87657646-1a79d500-c729-11ea-83c9-c99631dd4863.png)

### Figma 
![Screen Shot 2020-07-16 at 5 51 08 AM](https://user-images.githubusercontent.com/37882933/87657677-22d21000-c729-11ea-98d6-156e6a2ad4f4.png)
![Screen Shot 2020-07-16 at 5 50 58 AM](https://user-images.githubusercontent.com/37882933/87657687-25346a00-c729-11ea-9932-4cd6aceae185.png)

**Comment by zackkrida** [comment]
Hi @Audiosutras,

We do not yet have a component in vocabulary for the type of padded cards with colored backgrounds like you are using for the license info here: https://github.com/creativecommons/cc-licenses/blob/develop/cc_licenses/templates/includes/use_of_licenses.html

For now I would recommend adding some custom css somewhere that overrides the default styles for `divider`:

```scss
// Replace '.has-background-info-light' with any parent class above the divider, as needed
.has-background-info=light .divider {
    margin-left: -2rem;
    width: calc(100% + 4rem);
    background-color: #b0b0b0;
}
```
