### ISSUE TITLE
RTL/LTR Language Support for BreadCrumb Component

### ISSUE THREAD

**Issue by Audiosutras** [cc-archive/vocabulary-legacy#644]
## Description

When viewing a `right to left` language, the breadcrumb [component's](https://cc-vocabulary.netlify.app/?path=/docs/navigation-breadcrumb--default-story) arrows should "flip" there direction. Currently the breadcrumb arrows only point right. When `right to left` language is being shown these arrows should point `left` . 
## Reproduction

1. On a parent element of the breadcrumb component, add the `dir` attribute
2. Toggle `dir` attribute between `dir="ltr"` and `dir="rtl"`

## Screenshots

`Left to Right`

![Screen Shot 2020-09-09 at 12 49 21 PM](https://user-images.githubusercontent.com/37882933/92628548-fc4cd300-f29a-11ea-97a2-d978320e355a.png)

`Right to Left`

![Screen Shot 2020-09-09 at 12 48 59 PM](https://user-images.githubusercontent.com/37882933/92628572-07076800-f29b-11ea-8bd5-895741607201.png)

Please ignore `See the Deed` in the second screenshot. I'm currently working on `rtl` support and wanted to stop to make sure that this issue was created.

## Additional context

The below PR is adding `rtl/ltr` support for the new licenses pages:

https://github.com/creativecommons/cc-licenses/pull/22

**Comment by zackkrida** [comment]
Here's some more styles to fix the breadcrumbs. I will make this code part of vocabulary eventually and let you all know when. I'd suggest adding these styles to your project directly until then.

```css
html[dir="rtl"] nav.breadcrumb>ul li+li:before {
    transform: rotate(180deg);
}

html[dir="rtl"] .breadcrumb li:first-child a {
    padding-right: 0;
    padding-left: .5rem;
}
```
